#pragma once

#include "Constants.h"

#define ArraySize(x) (sizeof((x)) / sizeof((x)[0]))

struct AreaNode
{
	int nCount;
	int nAreas[64];
};

extern int GetAreas(DWORD nArray[], int nSize, int nStartAreaId, WORD wX, WORD wY);

static AreaNode AreaNodes[] = {
	// Act 1
	{4,	{MAP_A1_ROGUE_ENCAMPMENT, MAP_A1_BLOOD_MOOR, MAP_A1_COLD_PLAINS, MAP_A1_STONY_FIELD}},
	{6, {MAP_A1_DARK_WOOD, MAP_A1_BLACK_MARSH, MAP_A1_TAMOE_HIGHLAND, MAP_A1_MONASTERY_GATE, MAP_A1_OUTER_CLOISTER, MAP_A1_BARRACKS}},
	// Act 2
	{6, {MAP_A2_LUT_GHOLEIN, MAP_A2_ROCKY_WASTE, MAP_A2_DRY_HILLS, MAP_A2_FAR_OASIS, MAP_A2_LOST_CITY, MAP_A2_VALLEY_OF_SNAKES}},
	// Act 3
	{9, {MAP_A3_KURAST_DOCKS, MAP_A3_SPIDER_FOREST, MAP_A3_GREAT_MARSH, MAP_A3_FLAYER_JUNGLE, MAP_A3_LOWER_KURAST, MAP_A3_KURAST_BAZAAR, MAP_A3_UPPER_KURAST, MAP_A3_KURAST_CAUSEWAY, MAP_A3_TRAVINCAL}},
	// Act 4
	{4, {MAP_A4_THE_PANDEMONIUM_FORTRESS, MAP_A4_OUTER_STEPPES, MAP_A4_PLAINS_OF_DESPAIR, MAP_A4_CITY_OF_THE_DAMNED}},
	// Act 5
	{4, {MAP_A5_HARROGATH, MAP_A5_THE_BLOODY_FOOTHILLS, MAP_A5_FRIGID_HIGHLANDS, MAP_A5_ARREAT_PLATEAU}},
};
